### PR TITLE
Issue 82: YSLOW does not work in Firebug 1.12beta

### PR DESCRIPTION
**Pull request by janodvarko**
It seems to be all working well now.
Let me know if you see any other compatibility problems with Firebug 1.12, I can fix it.

Honza

### CODE REVIEW

**Comment by marcelduran** [comment]
thanks @janodvarko, just submitted a new release [3.1.7](https://addons.mozilla.org/en-US/firefox/addon/yslow/versions/?page=1#version-3.1.7)

**Comment by janodvarko** [comment]
Great. Could anyone verify the fix?
Honza

**Comment by lkraav** [comment]
@marcelduran could you also push relevant git tags, so github could auto-create Releases?

**Comment by lkraav** [comment]
Fix confirmed working on Linux Firefox 23.0.1

**Pull request merged**
